test_discount:
    resource: "@TestBundle/Resources/config/routing/discount.yml"
    prefix:   /discount

test_photo:
    resource: "@TestBundle/Resources/config/routing/photo.yml"
    prefix:   /photo

test_category:
    resource: "@TestBundle/Resources/config/routing/category.yml"
    prefix:   /category

test_product:
    resource: "@TestBundle/Resources/config/routing/product.yml"
    prefix:   /product

test_site:
    resource: "@TestBundle/Resources/config/routing/site.yml"